app = "wolofconnect"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  FLET_SESSION_TIMEOUT = "60"
  secret_key='c09e65a29308957a29712bb798c2cf6f2dd7563eee33a7f63057f62552c25c72'
  ALGORITHM = 'HS256'

[experimental]
    allowed_public_ports = []
    auto_rollback = true

[[services]]
    http_checks = []
    internal_port = 8000
    processes = ["app"]
    protocol = "tcp"
    script_checks = []



  [http_service.concurrency]
    type = "connections"
    soft_limit = 200
    hard_limit = 250
    
  [[services.ports]]
    force_https = True
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15"
    restart_limit = 0
    timeout = "s2"
